# -*- coding: utf-8 -*-
"""projects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hc1Ac4dK1uc3I09sXuDW-gn7TsFMnEwD
"""

import requests

def convert_currency(amount, from_currency, to_currency):
    url = f"https://api.exchangerate-api.com/v4/latest/{from_currency.upper()}"
    response = requests.get(url)

    if response.status_code != 200:
        print("Error fetching data. Please check your internet or currency code.")
        return

    data = response.json()
    rates = data['rates']

    if to_currency.upper() not in rates:
        print("Invalid target currency code.")
        return

    converted = amount * rates[to_currency.upper()]
    print(f"{amount} {from_currency.upper()} = {converted:.2f} {to_currency.upper()}")

# Example usage:
print("=== Currency Converter ===")
amount = float(input("Enter amount: "))
from_currency = input("From currency (e.g., USD, INR, EUR): ")
to_currency = input("To currency (e.g., USD, INR, EUR): ")
convert_currency(amount, from_currency, to_currency)

